#!/bin/bash
cd /opt/logging/Adafruit_Python_DHT
python setup.py install

while true
do
    date=`date`
    cpu_tmp=`cat /sys/class/thermal/thermal_zone0/temp`
    cpu_speed=`cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq`
    dht_out=`./examples/AdafruitDHT.py 22 26`
    box_tmp=`echo $dht_out | cut -c 6-9`
    box_hum=`echo $dht_out | cut -c 21-24`

    echo "${date},$((cpu_tmp/1000)),$((cpu_speed/1000)),${box_tmp},${box_hum}" >> /data/data.log
    sleep 120
done
