#!/bin/bash
date=`date`
cpu_tmp=`cat /sys/class/thermal/thermal_zone0/temp`
cpu_speed=`cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq`
dht_out=`/opt/Adafruit_Python_DHT/examples/AdafruitDHT.py 22 26`
box_tmp=`echo $dht_out | cut -d " " -f 1 | cut -d "=" -f 2 | tr -d "*"`
box_hum=`echo $dht_out | cut -d " " -f 2 | cut -d "=" -f 2 | tr -d "%"`

echo "${date},$((cpu_tmp/1000)),$((cpu_speed/1000)),${box_tmp},${box_hum}" >> /data/data.log
