#!/bin/bash
cd /root/Adafruit_Python_DHT/
python setup.py install

while 1
do
    date=`date`
    cpu_tmp=`cat /sys/class/thermal/thermal_zone0/temp
    cpu_speed=`cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq`
    dht_out=`/root/Adafruit_Python_DHT/examples/AdafruitDHT/py 22 26`
    box_tmp=`echo $dhtout | cut -c 6-9`
    box_hum=`echo $dht_out | cut 21-24`

    echo "$date\t$cpu_temp\t$box_tmp\t$box_hum\r\n" >> /data/data.log
    sleep 120
done

